# Generated by Django 4.1.1 on 2022-09-12 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='uSleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepStart', models.CharField(default='Null', max_length=100)),
                ('sleepEnd', models.CharField(default='Null', max_length=100)),
                ('currentDate', models.CharField(default='Null', max_length=100)),
                ('duration', models.CharField(blank=True, default='Null', max_length=100, null=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
