# Generated by Django 4.1.1 on 2022-09-12 09:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usleep',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usleep',
            name='sleepEnd',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 9, 45, 14, 710628, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usleep',
            name='sleepStart',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 9, 45, 14, 710628, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usleep',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
