# Generated by Django 4.1.1 on 2022-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usleep_duration_alter_usleep_sleepend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usleep',
            name='currentDate',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='usleep',
            name='duration',
            field=models.CharField(blank=True, default='Null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usleep',
            name='sleepEnd',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='usleep',
            name='sleepStart',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
